### ISSUE TITLE
2-Feature-Layout

### ISSUE THREAD

**Issue by maximoortelli** [maximoortelli/spotify1#3]
## Description

For the implementation of the new feature `2-Feature-Layout`, the following components have been added and configured:

- **Sidebar on the left**: In the home tab, a Sidebar on the left has been added that contains the sections **Home**, **Search** and **Your Library**. In the **Your Library** section, users can access their song library.

- **Back and forward arrows**: Back and forward arrows have been added to the home page to facilitate navigation.

- **Sign up and Log in buttons**: Two buttons have been added to the user interface to allow users to register (Sign up) and log in (Log in).

- **Liked Songs button**: A Liked Songs button has been added where the user can view the songs they have liked.

These components are essential to the functionality and user experience of the new feature.

## Tasks

- [x] Add Sidebar on the left with Home, Search and Your Library sections
- [x] Add back and forward arrows in the home part
- [x] Add Sign up and Log in buttons
- [x] Add Liked Songs button

## Image

![Captura de pantalla (541)](https://github.com/maximoortelli/spotify1/assets/118080546/ebf4423f-29d9-4b4f-aaa4-e4dd89b4bff4)
